import { useRef, useState, useCallback } from "react";
import "./Quote.css";
import html2canvas from "html2canvas";
import { downloadImageByUrlAndName } from "../utils";

function formatterQuote(text) {
    return text.replace(/\n/g, "<br/>");
}

function getBgUrl(num = 1) {
    return `https://bucket2023.oss-cn-hangzhou.aliyuncs.com/mihua/images/mihuan${num}.jpg`;
}

const useQuote = (initialQuote) => {
    const [quote, setQuote] = useState(initialQuote);
    const formattedQuote = useRef(formatterQuote(quote));

    const onQuoteChange = useCallback((e) => {
        const newQuote = e.currentTarget.value;
        setQuote(newQuote);
        formattedQuote.current = formatterQuote(newQuote);
    }, []);

    return { quote, onQuoteChange, formattedQuote };
};

const useBackground = (initialNum) => {
    const [num, setNum] = useState(initialNum);

    const updateNum = useCallback((direction) => {
        setNum((prevNum) => {
            if (direction === "left") {
                return prevNum === 1 ? 99 : prevNum - 1;
            } else {
                return prevNum === 99 ? 1 : prevNum + 1;
            }
        });
    }, []);

    const bgUrl = getBgUrl(num);

    return { bgUrl, updateNum };
};

export default function Quote() {
    const { quote, onQuoteChange, formattedQuote } = useQuote("这是一句特别不牛逼的话");
    const { bgUrl, updateNum } = useBackground(1);
    const eleRef = useRef();

    const onDownload = useCallback(() => {
        html2canvas(eleRef.current, { useCORS: true, allowTaint: true }).then(
            (canvas) => {
                downloadImageByUrlAndName(
                    canvas.toDataURL("image/png"),
                    "quote.png",
                );
            },
        );
    }, []);

    return (
        <div className="quote">
            <div className="displayPane">
                <div
                    ref={eleRef}
                    className="quoteContentBox"
                    style={{ backgroundImage: `url(${bgUrl})` }}
                >
                    <div
                        className="quoteContent"
                        dangerouslySetInnerHTML={{ __html: formattedQuote.current }}
                    ></div>
                    <p className="slogn">“Quote generated by Hacker Pot</p>
                </div>
                <div className="arrows">
                    <span
                        className="material-symbols-outlined"
                        onClick={() => updateNum("left")}
                    >
                        arrow_back
                    </span>
                    <span
                        className="material-symbols-outlined"
                        onClick={() => updateNum("right")}
                    >
                        arrow_forward
                    </span>
                    <span
                        className="material-symbols-outlined"
                        onClick={onDownload}
                    >
                        download
                    </span>
                </div>
            </div>
            <div className="operatePane">
                <textarea
                    cols="30"
                    rows="10"
                    className="inputBox"
                    value={quote}
                    onChange={onQuoteChange}
                    placeholder="随便写点什么..."
                ></textarea>
            </div>
        </div>
    );
}
