import { useRef, useState } from "react";
import "./Quote.css";
import html2canvas from "html2canvas";
import { downloadImageByUrlAndName } from "../utils";

function formatterQuote(text) {
    return text.replace(/\n/g, "<br/>");
}

const BG_URL =
    "https://bucket2023.oss-cn-hangzhou.aliyuncs.com/mihua/images/mihuan1.jpg";

function getBgUrl(num = 1) {
    return `https://bucket2023.oss-cn-hangzhou.aliyuncs.com/mihua/images/mihuan${num}.jpg`;
}

export default function Quote() {
    const [quote, setQuote] = useState("这是一句特别不牛逼的话");
    const q = useRef(formatterQuote(quote));
    const [num, setNum] = useState(1);
    const onQuoteChange = (e) => {
        setQuote(e.currentTarget.value);
        q.current = formatterQuote(e.currentTarget.value);
    };

    const updateNum = (direction) => {
        if (direction === "left") {
            if (num === 1) {
                setNum(99);
            } else {
                setNum(num - 1);
            }
        } else {
            if (num === 99) {
                setNum(1);
            } else {
                setNum(num + 1);
            }
        }
    };
    const eleRef = useRef();

    const onDownload = () => {
        html2canvas(eleRef.current, { useCORS: true, allowTaint: true }).then(
            (canvas) => {
                downloadImageByUrlAndName(
                    canvas.toDataURL("image/png"),
                    "quote.png",
                );
            },
        );
    };

    return (
        <div className="quote">
            <div className="displayPane">
                <div
                    ref={eleRef}
                    className="quoteContentBox"
                    style={{ backgroundImage: `url(${getBgUrl(num)})` }}
                >
                    <div
                        className="quoteContent"
                        dangerouslySetInnerHTML={{ __html: q.current }}
                    ></div>
                    <p className="slogn">“Quote generated by Hacker Pot</p>
                </div>
                <div className="arrows">
                    <span
                        className="material-symbols-outlined"
                        onClick={() => updateNum("left")}
                    >
                        arrow_back
                    </span>
                    <span
                        className="material-symbols-outlined"
                        onClick={() => updateNum("right")}
                    >
                        arrow_forward
                    </span>
                    <span
                        className="material-symbols-outlined"
                        onClick={onDownload}
                    >
                        download
                    </span>
                </div>
            </div>
            <div className="operatePane">
                <textarea
                    cols="30"
                    rows="10"
                    className="inputBox"
                    value={quote}
                    onChange={onQuoteChange}
                    placeholder="随便写点什么..."
                ></textarea>
            </div>
        </div>
    );
}
